"""Committed reports, generated from logged runs.

The table is read back out of MLflow rather than out of the objects in memory, so the file
on disk says what the tracking store says. Anything a person writes below the generated
block is preserved when the report is regenerated.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from mlflow.tracking import MlflowClient

from . import config

if TYPE_CHECKING:  # pragma: no cover - import cycle only matters to a type checker
    from .train import SweepResult

BEGIN = "<!-- generated by `python -m mlops_loop train`: do not edit above this line -->"
END = "<!-- end generated block: hand-written notes go below -->"

DEFAULT_NOTES = """
## What the sweep showed

Two sentences go here, written by hand after reading the table above. Regenerating the
report keeps everything below this marker.
"""


def child_rows(parent_run_id: str) -> list[dict[str, Any]]:
    """Every child run of a parent, as it is stored in MLflow, sorted by validation PR-AUC."""
    client = MlflowClient()
    parent = client.get_run(parent_run_id)
    runs = client.search_runs(
        [parent.info.experiment_id],
        filter_string=f"tags.parent_run_id = '{parent_run_id}'",
        max_results=200,
    )
    rows = [
        {
            "name": run.data.tags.get("config_name", run.info.run_name),
            "family": run.data.params.get("model_family", "unknown"),
            "run_id": run.info.run_id,
            "metrics": run.data.metrics,
            "params": run.data.params,
        }
        for run in runs
    ]
    return sorted(rows, key=lambda row: -row["metrics"].get("val_pr_auc", float("-inf")))


def _model_params(params: dict[str, str]) -> str:
    """The model_* params of a run as one readable cell."""
    interesting = {
        key[len("model_") :]: value
        for key, value in params.items()
        if key.startswith("model_") and key not in ("model_class", "model_family")
    }
    skip = {"random_state", "solver", "max_iter", "early_stopping", "min_samples_leaf"}
    kept = {key: value for key, value in interesting.items() if key not in skip}
    return ", ".join(f"{key}={value}" for key, value in sorted(kept.items())) or "defaults"


def render_sweep_comparison(result: "SweepResult") -> str:
    """The generated block: provenance, the ranked table, and the promotion decision."""
    rows = child_rows(result.parent_run_id)
    winner_id = result.winner.run_id

    lines = [
        "# Sweep comparison",
        "",
        BEGIN,
        "",
        f"Parent run `{result.parent_run_id}`, experiment `{result.experiment_id}`, "
        f"commit `{result.git_commit[:7]}`.",
        f"Dataset sha256 `{result.dataset_sha256}`.",
        f"Feature-code hash `{result.feature_code_hash}`.",
        f"{len(rows)} configs, {result.seconds}s wall clock.",
        "",
        "Splits: "
        + ", ".join(f"{name} {count:,}" for name, count in result.rows.items())
        + ". Selection is validation PR-AUC. The holdout column is blank for every config "
        "except the winner, because the holdout was looked at exactly once: "
        f"{result.holdout_spends}.",
        "",
        "| rank | config | family | params | val PR-AUC | val ROC-AUC | val recall@P50 | "
        "val Brier | holdout PR-AUC | run id |",
        "|-----:|--------|--------|--------|-----------:|------------:|---------------:|"
        "----------:|---------------:|--------|",
    ]

    for rank, row in enumerate(rows, start=1):
        metrics = row["metrics"]
        holdout = (
            f"{metrics['holdout_pr_auc']:.4f}" if "holdout_pr_auc" in metrics else "not looked at"
        )
        mark = " **(champion)**" if row["run_id"] == winner_id else ""
        lines.append(
            f"| {rank} | `{row['name']}`{mark} | {row['family']} | {_model_params(row['params'])} "
            f"| {metrics.get('val_pr_auc', float('nan')):.4f} "
            f"| {metrics.get('val_roc_auc', float('nan')):.4f} "
            f"| {metrics.get('val_recall_at_precision_50', float('nan')):.4f} "
            f"| {metrics.get('val_brier', float('nan')):.4f} "
            f"| {holdout} | `{row['run_id']}` |"
        )

    incoming = result.promotion["incoming"]
    outgoing = result.promotion["outgoing"]
    lines += [
        "",
        "## Promotion",
        "",
        f"`{incoming['config_name']}` was registered as `{result.model_name}` version "
        f"{result.model_version} and took the `champion` alias.",
    ]
    if outgoing:
        recorded = outgoing["holdout_recorded"]
        was = (
            f"holdout PR-AUC {recorded['pr_auc']:.4f}, Brier {recorded['brier']:.4f}"
            if "pr_auc" in recorded
            else "no holdout metrics recorded on its run"
        )
        lines.append(
            f"Version {outgoing['version']} was the champion and now holds the `previous` "
            f"alias. Its run recorded {was}; the incoming version scores holdout PR-AUC "
            f"{incoming['holdout']['pr_auc']:.4f}, Brier {incoming['holdout']['brier']:.4f}. "
            "Those outgoing numbers are read back from its own run rather than re-scored, "
            "which would have been a second look at the holdout."
        )
    else:
        lines.append("There was no previous champion, so no `previous` alias was set.")
    lines += ["", END, ""]
    return "\n".join(lines)


def write_sweep_comparison(result: "SweepResult", path: Path | str | None = None) -> Path:
    """Write the generated block, keeping any hand-written notes that follow it."""
    target = Path(path) if path is not None else config.repo_root() / "reports" / "sweep_comparison.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    notes = DEFAULT_NOTES
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if END in existing:
            notes = existing.split(END, 1)[1]

    target.write_text(render_sweep_comparison(result) + notes.lstrip("\n"), encoding="utf-8")
    return target
