"""Committed reports, generated from logged runs.

The table is read back out of MLflow rather than out of the objects in memory, so the file
on disk says what the tracking store says. Anything a person writes below the generated
block is preserved when the report is regenerated.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from mlflow.tracking import MlflowClient

from . import config

if TYPE_CHECKING:  # pragma: no cover - import cycle only matters to a type checker
    from .analysis import ErrorAnalysis
    from .monitor import MonitorResult
    from .retrain import Decision
    from .train import SweepResult

BEGIN = "<!-- generated by `python -m mlops_loop train`: do not edit above this line -->"
END = "<!-- end generated block: hand-written notes go below -->"

DEFAULT_NOTES = """
## What the sweep showed

Two sentences go here, written by hand after reading the table above. Regenerating the
report keeps everything below this marker.
"""


def child_rows(parent_run_id: str) -> list[dict[str, Any]]:
    """Every child run of a parent, as it is stored in MLflow, sorted by validation PR-AUC."""
    client = MlflowClient()
    parent = client.get_run(parent_run_id)
    runs = client.search_runs(
        [parent.info.experiment_id],
        filter_string=f"tags.parent_run_id = '{parent_run_id}'",
        max_results=200,
    )
    rows = [
        {
            "name": run.data.tags.get("config_name", run.info.run_name),
            "family": run.data.params.get("model_family", "unknown"),
            "run_id": run.info.run_id,
            "metrics": run.data.metrics,
            "params": run.data.params,
        }
        for run in runs
    ]
    return sorted(rows, key=lambda row: -row["metrics"].get("val_pr_auc", float("-inf")))


def _model_params(params: dict[str, str]) -> str:
    """The model_* params of a run as one readable cell."""
    interesting = {
        key[len("model_") :]: value
        for key, value in params.items()
        if key.startswith("model_") and key not in ("model_class", "model_family")
    }
    skip = {"random_state", "solver", "max_iter", "early_stopping", "min_samples_leaf"}
    kept = {key: value for key, value in interesting.items() if key not in skip}
    return ", ".join(f"{key}={value}" for key, value in sorted(kept.items())) or "defaults"


def render_sweep_comparison(result: "SweepResult") -> str:
    """The generated block: provenance, the ranked table, and the promotion decision."""
    rows = child_rows(result.parent_run_id)
    winner_id = result.winner.run_id

    lines = [
        "# Sweep comparison",
        "",
        BEGIN,
        "",
        f"Parent run `{result.parent_run_id}`, experiment `{result.experiment_id}`, "
        f"commit `{result.git_commit[:7]}`.",
        f"Dataset sha256 `{result.dataset_sha256}`.",
        f"Feature-code hash `{result.feature_code_hash}`.",
        f"{len(rows)} configs, {result.seconds}s wall clock.",
        "",
        "Splits: "
        + ", ".join(f"{name} {count:,}" for name, count in result.rows.items())
        + ". Selection is validation PR-AUC. The holdout column is blank for every config "
        "except the winner, because the holdout was looked at exactly once: "
        f"{result.holdout_spends}.",
        "",
        "| rank | config | family | params | val PR-AUC | val ROC-AUC | val recall@P50 | "
        "val Brier | holdout PR-AUC | run id |",
        "|-----:|--------|--------|--------|-----------:|------------:|---------------:|"
        "----------:|---------------:|--------|",
    ]

    for rank, row in enumerate(rows, start=1):
        metrics = row["metrics"]
        holdout = (
            f"{metrics['holdout_pr_auc']:.4f}" if "holdout_pr_auc" in metrics else "not looked at"
        )
        mark = " **(champion)**" if row["run_id"] == winner_id else ""
        lines.append(
            f"| {rank} | `{row['name']}`{mark} | {row['family']} | {_model_params(row['params'])} "
            f"| {metrics.get('val_pr_auc', float('nan')):.4f} "
            f"| {metrics.get('val_roc_auc', float('nan')):.4f} "
            f"| {metrics.get('val_recall_at_precision_50', float('nan')):.4f} "
            f"| {metrics.get('val_brier', float('nan')):.4f} "
            f"| {holdout} | `{row['run_id']}` |"
        )

    incoming = result.promotion["incoming"]
    outgoing = result.promotion["outgoing"]
    lines += [
        "",
        "## Promotion",
        "",
        f"`{incoming['config_name']}` was registered as `{result.model_name}` version "
        f"{result.model_version} and took the `champion` alias.",
    ]
    if outgoing:
        recorded = outgoing["holdout_recorded"]
        was = (
            f"holdout PR-AUC {recorded['pr_auc']:.4f}, Brier {recorded['brier']:.4f}"
            if "pr_auc" in recorded
            else "no holdout metrics recorded on its run"
        )
        lines.append(
            f"Version {outgoing['version']} was the champion and now holds the `previous` "
            f"alias. Its run recorded {was}; the incoming version scores holdout PR-AUC "
            f"{incoming['holdout']['pr_auc']:.4f}, Brier {incoming['holdout']['brier']:.4f}. "
            "Those outgoing numbers are read back from its own run rather than re-scored, "
            "which would have been a second look at the holdout."
        )
    else:
        lines.append("There was no previous champion, so no `previous` alias was set.")
    lines += ["", END, ""]
    return "\n".join(lines)


def write_sweep_comparison(result: "SweepResult", path: Path | str | None = None) -> Path:
    """Write the generated block, keeping any hand-written notes that follow it."""
    target = Path(path) if path is not None else config.repo_root() / "reports" / "sweep_comparison.md"
    target.parent.mkdir(parents=True, exist_ok=True)

    notes = DEFAULT_NOTES
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if END in existing:
            notes = existing.split(END, 1)[1]

    target.write_text(render_sweep_comparison(result) + notes.lstrip("\n"), encoding="utf-8")
    return target


def write_drift_report(
    result: "MonitorResult",
    decision: "Decision | None" = None,
    directory: Path | str | None = None,
) -> Path:
    """reports/drift_<batch>.md: every PSI, the verdict, and the decision if one was made.

    Fully generated. Unlike the sweep comparison there is no hand-written section, because a
    drift report describes one batch at one moment and a stale reading below it would be
    worse than none.
    """
    from .monitor import PREDICTION_KEY

    folder = Path(directory) if directory is not None else config.repo_root() / "reports"
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / f"drift_{result.batch}.md"

    lines = [
        f"# Drift report: {result.batch}",
        "",
        "Generated by `python -m mlops_loop drift`. Every number here is in a logged run.",
        "",
        f"- Batch: {result.description or result.batch}, {result.batch_rows:,} rows",
        f"- Reference: the `{result.reference_split}` split, {result.reference_rows:,} rows",
        f"- Champion: `{result.model_name}` version {result.model_version}, "
        f"run `{result.champion_run_id}`",
        f"- Monitor run: `{result.run_id}`",
        f"- Verdict: **{'drifted' if result.drifted else 'no drift'}**, "
        f"{len(result.breaches)} breach(es) of {len(result.all_psi)} checks",
        "",
        "## Population stability index",
        "",
        "PSI of the batch against the reference. Numeric columns use ten quantile bins of the "
        "reference, categorical columns one bin per value. The band is the conventional "
        "reading: below 0.10 none, 0.10 to 0.25 moderate, above 0.25 major.",
        "",
        "| feature | kind | PSI | threshold | bins | band | result |",
        "|---------|------|----:|----------:|-----:|------|--------|",
    ]
    for item in result.all_psi:
        name = "prediction distribution" if item.feature == PREDICTION_KEY else f"`{item.feature}`"
        lines.append(
            f"| {name} | {item.kind} | {item.psi:.4f} | {item.threshold:.2f} | {item.bins} "
            f"| {item.band} | {'**breach**' if item.breached else 'ok'} |"
        )

    lines += [
        "",
        "## What the champion does on this batch",
        "",
        "The batch carries labels because it is a held-out slice of a historical file. Real "
        "monitoring would not have them at scoring time, which is why the trigger above reads "
        "only inputs and predictions. These are here to say what the drift cost.",
        "",
        "| | reference | batch |",
        "|---|---:|---:|",
        f"| rows | {result.reference_rows:,} | {result.batch_rows:,} |",
        f"| churn rate | {result.reference_churn:.4f} | {result.batch_churn:.4f} |",
    ]
    for key in sorted(result.reference_metrics):
        lines.append(
            f"| {key} | {result.reference_metrics[key]:.4f} | {result.batch_metrics[key]:.4f} |"
        )

    lines += ["", "## Retraining decision", ""]
    if decision is None:
        if result.drifted:
            lines.append(
                "Drift was detected but no decision is recorded in this file, which means the "
                "run stopped before the challenger finished. Treat that as a failure, not a "
                "rejection."
            )
        else:
            lines.append(
                "No PSI exceeded its threshold, so no challenger was trained and the champion "
                "keeps the alias untouched."
            )
    else:
        lines += [
            f"Drift triggered a challenger: the champion's own configuration "
            f"(`{decision.family}`, `{decision.params}`) refitted on "
            f"{decision.challenger_rows:,} rows, the reference split plus this batch. Champion "
            f"and challenger were then scored on the same fixed holdout, which neither was "
            f"trained on.",
            "",
            f"Decision run `{decision.run_id}`, challenger run `{decision.challenger_run_id}`.",
            "",
            "| metric | champion | challenger | delta |",
            "|--------|---------:|-----------:|------:|",
        ]
        for key in sorted(decision.champion_metrics):
            champ, chall = decision.champion_metrics[key], decision.challenger_metrics[key]
            lines.append(f"| {key} | {champ:.4f} | {chall:.4f} | {chall - champ:+.4f} |")
        lines += [
            "",
            f"Rule: promote only if `{decision.metric}` improves by more than "
            f"{decision.margin:.4f}. Improvement was **{decision.improvement:+.4f}**.",
            "",
            f"**Verdict: {decision.verdict}.**"
            + (
                f" The challenger was registered as version {decision.challenger_version} and "
                "took the `champion` alias; the outgoing champion kept its version and took "
                "`previous`."
                if decision.promoted
                else " The champion keeps the alias. The challenger stays in its run, scored "
                "and rejected, so the next session can see what was tried."
            ),
        ]
    lines.append("")
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def write_error_analysis(analysis: "ErrorAnalysis", path: Path | str | None = None) -> Path:
    """reports/error_analysis.md: 20 sampled failures, each attributed to one component."""
    target = (
        Path(path) if path is not None else config.repo_root() / "reports" / "error_analysis.md"
    )
    target.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Error analysis",
        "",
        "Generated by `python -m mlops_loop reports`. Every number is in a logged run.",
        "",
        f"- Champion: `{analysis.model_name}` version {analysis.model_version}, "
        f"run `{analysis.champion_run_id}`",
        f"- Analysis run: `{analysis.run_id}`",
        f"- Fitted on `{analysis.trained_on}`, {analysis.train_rows:,} rows",
        f"- Scored on the fixed holdout, {analysis.rows:,} rows, at threshold "
        f"{analysis.threshold:.4f}",
        f"- {analysis.errors} rows wrong at that threshold "
        f"({analysis.errors / analysis.rows:.1%}): {analysis.false_negatives} false negatives, "
        f"{analysis.false_positives} false positives",
        f"- {analysis.sample_size} sampled with seed {analysis.seed} and attributed below",
        "",
        "## How each failure was attributed",
        "",
        "Each sampled row is charged to the first component in pipeline order that could have "
        "prevented it. The rules are code, in `mlops_loop/analysis.py`, so the tally is "
        "reproducible rather than a judgement call:",
        "",
        "1. **split**: the row is outside the distribution the champion was fitted on. A "
        "categorical value never appears in its training rows, or a numeric feature sits "
        "beyond the range they cover. The comparison is against the rows this champion "
        f"actually saw (`{analysis.trained_on}`), not against the train split, because a "
        "challenger promoted by `drift` was fitted on more than train.",
        "2. **features**: the row sits where the feature set cannot separate anything. Its 25 "
        "nearest training neighbours in the encoded space churn at within "
        f"{analysis.uninformative_band:.2f} of the training base rate, so there is no signal "
        "to read.",
        "3. **model**: in distribution, informative neighbourhood, and the model still ranked "
        "it wrongly. No choice of threshold would fix it.",
        "4. **threshold**: ranked correctly, only the cut is wrong. It is right at the "
        f"validation-optimal threshold ({analysis.val_threshold:.4f}) and wrong at "
        f"{analysis.threshold:.4f}.",
        "",
        "## Tally",
        "",
        "| component | sampled failures | share |",
        "|-----------|-----------------:|------:|",
    ]
    for component, count in analysis.tally.items():
        lines.append(f"| {component} | {count} | {count / analysis.sample_size:.0%} |")
    lines += [
        f"| **total** | **{analysis.sample_size}** | **100%** |",
        "",
        f"The same rules applied to all {analysis.errors} failures rather than the sample of "
        f"{analysis.sample_size} give "
        + ", ".join(f"{key} {value}" for key, value in analysis.full_tally.items())
        + ". The sample is there because the brief asks for twenty rows a person can read.",
        "",
        "## The twenty",
        "",
        "| # | customerID | truth | p(churn) | kind | component | why |",
        "|--:|-----------|:-----:|---------:|------|-----------|-----|",
    ]
    for index, case in enumerate(analysis.cases, start=1):
        lines.append(
            f"| {index} | `{case.customer_id}` | {case.truth} | {case.probability:.4f} "
            f"| {case.kind} | **{case.component}** | {case.reason} |"
        )

    biggest, biggest_count = analysis.biggest_cell
    lines += [
        "",
        "## The biggest cell",
        "",
        f"**{biggest}**, {biggest_count} of {analysis.sample_size} sampled failures "
        f"({biggest_count / analysis.sample_size:.0%}).",
        "",
        analysis.diagnosis,
        "",
        "## The cheapest fix",
        "",
        analysis.cheapest_fix,
        "",
        "Not applied in this session. The brief asks for error analysis before the fix, and a "
        "fix chosen and applied in the same breath is a fix nobody measured.",
        "",
    ]
    target.write_text("\n".join(lines), encoding="utf-8")
    return target
